### ISSUE TITLE
задача: поженить двух Human

### ISSUE THREAD

**Issue by kicumkicum** [nomean42/js-learn#3]
* добавить свойство **gender**, которое будет принимать одно из двух значений *'male'* или *'female'*.
* добавить метод **Human.protoype.married**, 
который будет вызываться у одного экземпляра класса,
принимать на вход другой экземпляр класса,
и у одного женского экземпляра менять фамилию на такую же, как и у мужского.
* будем консервативны, поэтому браки разрешены только между людьми (*instanceof*), и эти люди должны быть разного пола
* **доп. задание**: результат бракосочетания будет новый класс **Family**, имеющий свойства *dad*, *mummy*, *child*

**Comment by nomean42** [comment]
Done in pull request #5
