### ISSUE TITLE
закрепрление контекста исполнения

### ISSUE THREAD

**Issue by kicumkicum** [nomean42/js-learn#7]
Контекст исполнения - это только то, что стоит перед функцией:
```javascript
var foo = {};
foo.bar = {};
foo.bar.baz = function() {
    console.log(this);// контекст исполнения - foo.bar
};
var pew = foo.bar.baz;
pew();// чему равен this, и почему
```
Когда позапускаешь этот код, и поймешь что к чему, напиши в комментарии к тикету, почему про...ся контекст при использовании setTimeout

**Comment by nomean42** [comment]
Интерпретатор js записывает контекст исполнения прямо перед началом исполнения функции.
При такой записи он увидел pew(), понял что мы думаем что это функция и начинает готовиться к ее исполнению, в том числе назначает контекст. Инфы у него про контекст никакой так как при var pew = foo.bar.baz;(в момент назначения pew) даже не знает что там в foo.bar.baz вообще лежит функция, назначает контекст стандартно-глобальным. Потом начинает читать что там в foo.bar.baz и все что видит все исполняет. 
Вопрос: если код немного переделать 
var pew = foo.bar.baz();
pew;
то исполняется в нужном контексте, и я видимо не очень до сих пор понял, зачем тогда bind?

**Comment by kicumkicum** [comment]
наводящий вопрос - что такое круглые скобочки - () ?

**Comment by nomean42** [comment]
Я бы сказал, это функция.

**Comment by kicumkicum** [comment]
и сказал бы не совсем верно.
Круглые скобочки - это вызов функции.

**Comment by nomean42** [comment]
Видимо при объявлении foofoo вызывается какая-то функция function и ей что-то передают?

**Comment by kicumkicum** [comment]
Нет, на СВОИ строчки, с pew

**Comment by nomean42** [comment]
))) pew, когда без скобок, ничего не делает, а var pew = foo.bar.baz(); вызывает функцию foo.bar.baz.

**Comment by kicumkicum** [comment]
отлично) теперь переделай этот свой код на правильный.

**Comment by nomean42** [comment]
var pew = foo.bar.baz.bind(foo.bar);
pew();

**Comment by kicumkicum** [comment]
:metal: все верно :metal:

**Comment by nomean42** [comment]
закрываем вроде
